### ISSUE TITLE
No switching, again

### ISSUE THREAD

**Issue by subdesign** [jalendport/switch-php#6]
I have php@7.1 and php@5.6 installed with brew. Running php switcher gives the following:
```
$ switch-php 5.6 -v
 👀  Verifying that Valet is installed...
Password:
 🔍  Checking which PHP versions are installed...
 🛑  Stopping Valet...
 ==>  Stopping nginx...
 ✅  Valet stopped
 🔀  Switching to php@5.6...
 ==>  Stopping php@5.6...
 ==>  Unlinking php@5.6...
 ==>  Stopping php@7.1...
 ==>  Unlinking php@7.1...
 ==>  Linking php@5.6...
 ==>  Starting php@5.6...
 ✅  PHP switched
 ⚙  Starting Valet...
 ==>  Starting nginx...
 ✅  Valet started

You are now using PHP 7.1.20
```
Showing the version gives php 7.1.20
```
php -v 
PHP 7.1.20 (cli) (built: Jul 20 2018 10:27:12) ( NTS )
```
Exited terminal, restarted and reading the #2 issue fired the following:
```
$ brew link --overwrite php
Error: No such keg: /usr/local/Cellar/php
```
Brew doctor:
```
Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/php
```
Then tried manually unlink 7.1:
```
$ brew unlink php@7.1
Unlinking /usr/local/Cellar/php@7.1/7.1.20... 0 symlinks removed
```
and relink 5.6:
```
$ brew link --overwrite --force php@5.6

Linking /usr/local/Cellar/php@5.6/5.6.37... 25 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/php@5.6/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/php@5.6/sbin:$PATH"' >> ~/.bash_profile
```
..but phpinfo() show me 7.1.20 yet

**Comment by subdesign** [comment]
Somehow I managed to work this script. 
Some info on install: at the end of switching, I get message `You are now using PHP 7.1.20` even I switched to 5.6. (I guess because the CLI gives 7.1.20, but on my website `phpinfo()` gives 5.6)

**Comment by jalendport** [comment]
Hey, glad you got it working in the end.

One probable reason you're seeing a different version of PHP in your Terminal and on your website via `phpinfo()` is what directories you're including in your PATH. Basically, in your `.bash-profile`/`.bashrc`/etc. you can either manually set the version of PHP you want to use on your computer with

    export PATH="/usr/local/opt/php@7.1/bin:$PATH"

versus using something like

    export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

which will use whatever PHP version is currently linked. You can either check your [dotfiles](https://medium.com/@webprolific/getting-started-with-dotfiles-43c3602fd789) or run `echo $PATH` to see what your PATH is currently set to.

If you run `which php`, it will return the directory it's finding the PHP executable in. Ideally this should be `/usr/local/bin` as that's where Brew updates the [symlinks](https://en.wikipedia.org/wiki/Symbolic_link) when you run `link php@7.1` or whatever.

Also, I've found that in some cases you have to restart your dev server to pick up the new version of PHP. (Looks like you're using Valet on your machine, so you'll want to run a `valet restart` when you manually run the `link`/`unlink` commands.)

Let me know if you continue to experience any weirdness at all and I'll definitely help you debug it. Thanks!
